In [16]:
print("Hello I'm excited to learn pytoch")

Hello I'm excited to learn pytoch


In [6]:
import torch
print(torch.cuda.is_available())  # Should return True if GPU is detected
print(torch.cuda.get_device_name(0))  # Shows your GPU name

True
NVIDIA GeForce RTX 3050 6GB Laptop GPU


In [7]:
!nvidia-smi

Tue Feb  3 15:47:23 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.83                 Driver Version: 581.83         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8              3W /   47W |     283MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [8]:
## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cu126


## INTORDUCTION to tensors

## Creating tensors

PyTorch tensors are created usingt torch.Tensor() =https://pytorch.org/docs/stable/tensrors.html

In [4]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [7]:
# Get tensor back as python int
scalar.item()

7

In [8]:
# Vector
vector=torch.tensor([7,7])

In [9]:
vector

tensor([7, 7])

In [10]:
# vector has a magnitude and direction

In [15]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [25]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [26]:
MATRIX.ndim

2

In [27]:
MATRIX.size()

torch.Size([2, 2])

In [28]:
MATRIX[1]

tensor([ 9, 10])

In [34]:
# TENSOR
TENSOR= torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [35]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [36]:
TENSOR.size()

torch.Size([1, 3, 3])

In [37]:
TENSOR.shape

torch.Size([1, 3, 3])

TENSOR.shape

Returns a torch.Size object
It's a property/attribute (no parentheses needed)
Inherited from NumPy's convention (for compatibility)

TENSOR.size()

Returns a torch.Size object (same thing!)
It's a method (needs parentheses)
PyTorch's original/native way

Why both exist?
PyTorch wanted to be compatible with NumPy (which uses .shape), so they added .shape as an alias. But .size() was already the PyTorch way, so they kept both.


TENSOR.shape       # Get the full shape
TENSOR.size()      # Get the full shape (same result)
TENSOR.size(0)     # Get size of dimension 0 (useful!)
TENSOR.size(1)     # Get size of dimension 1
# TENSOR.shape(0)  # ❌ This won't work - shape is not callable

In [39]:
TENSOR.size(0)

1

In [40]:
TENSOR.size(1)

3

In [41]:
TENSOR2=torch.tensor([[[[[3,4,2],[234,534,6]]]]])

In [42]:
TENSOR2.ndim

5

In [44]:
TENSOR2.size() # here tensor2 is a 5 dimensional tensor

torch.Size([1, 1, 1, 2, 3])

# RANDOM TENSORS
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random number to better represent the data.lambda

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers1`

Torch random tensors: https://pytorch.org/docs/stable/generated/torch.rand.html

In [45]:
#Create a random tensor of size 4
random_tensor= torch.rand(3,4)

In [46]:
random_tensor

tensor([[0.8595, 0.2704, 0.2833, 0.5113],
        [0.8233, 0.9767, 0.4912, 0.8822],
        [0.2378, 0.2548, 0.9068, 0.1718]])

In [52]:
torch.set_printoptions(profile="default")
random_tens=torch.rand(100,100,100)
random_tens

tensor([[[0.7043, 0.9553, 0.6610,  ..., 0.0621, 0.1218, 0.1424],
         [0.8901, 0.6257, 0.8818,  ..., 0.5399, 0.2291, 0.2901],
         [0.9281, 0.8645, 0.6226,  ..., 0.0117, 0.2332, 0.7116],
         ...,
         [0.8970, 0.0234, 0.4162,  ..., 0.4415, 0.6823, 0.6252],
         [0.3319, 0.8862, 0.0505,  ..., 0.8704, 0.8434, 0.2325],
         [0.5780, 0.6599, 0.9004,  ..., 0.7615, 0.4006, 0.0613]],

        [[0.4500, 0.8561, 0.8497,  ..., 0.7526, 0.6604, 0.5741],
         [0.6376, 0.0863, 0.6604,  ..., 0.7660, 0.3305, 0.5858],
         [0.6683, 0.6740, 0.3622,  ..., 0.9860, 0.8012, 0.3478],
         ...,
         [0.2965, 0.8254, 0.8907,  ..., 0.0429, 0.3968, 0.6603],
         [0.3356, 0.8703, 0.7663,  ..., 0.2374, 0.6937, 0.2049],
         [0.3630, 0.1990, 0.8562,  ..., 0.3719, 0.8677, 0.1389]],

        [[0.9703, 0.1486, 0.0932,  ..., 0.2432, 0.0796, 0.7366],
         [0.3196, 0.0366, 0.7679,  ..., 0.9668, 0.2232, 0.3431],
         [0.3985, 0.4587, 0.5322,  ..., 0.3751, 0.5378, 0.

In [53]:
random_tensor

tensor([[0.8595, 0.2704, 0.2833, 0.5113],
        [0.8233, 0.9767, 0.4912, 0.8822],
        [0.2378, 0.2548, 0.9068, 0.1718]])

In [58]:
new_random_tensor = torch.rand(2,2,2,2,2)

In [59]:
new_random_tensor

tensor([[[[[0.1567, 0.3480],
           [0.4754, 0.3418]],

          [[0.5143, 0.6912],
           [0.8146, 0.5905]]],


         [[[0.6536, 0.9577],
           [0.9989, 0.6447]],

          [[0.7823, 0.1752],
           [0.7749, 0.9594]]]],



        [[[[0.5488, 0.2950],
           [0.1307, 0.1613]],

          [[0.8152, 0.7797],
           [0.5228, 0.4896]]],


         [[[0.5917, 0.2998],
           [0.3955, 0.5145]],

          [[0.6577, 0.5973],
           [0.2236, 0.2209]]]]])

In [60]:
# Create a random tensor with similar shape to and image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) # height, width, colour channels (r,g,b)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [61]:
torch.rand(4,5)

tensor([[0.4232, 0.2622, 0.4821, 0.8418, 0.2977],
        [0.8187, 0.1222, 0.0147, 0.2469, 0.9521],
        [0.7916, 0.8673, 0.8636, 0.9368, 0.6367],
        [0.0433, 0.5002, 0.2472, 0.9437, 0.7812]])

In [63]:
torch.rand(size=(4,6))

tensor([[0.5194, 0.2372, 0.7685, 0.4464, 0.9065, 0.7734],
        [0.1949, 0.6209, 0.9010, 0.6905, 0.8137, 0.8552],
        [0.5404, 0.2566, 0.1390, 0.0229, 0.0096, 0.1817],
        [0.2107, 0.4099, 0.3806, 0.4875, 0.2323, 0.7797]])

## Zeros and Ones

In [64]:
#Create a tensor of all zeros
zeros =torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [65]:
# Create a tensor of all ones
ones=torch.ones(4,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [67]:
#dtype is default data type
ones.dtype

torch.float32

# Creating a range of tensors and tensors like

In [70]:
# Use torch.range()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
torch.__version__

'2.10.0+cu126'

In [72]:
one_to_ten=torch.arange(1,11)

In [73]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
one_to_n=torch.arange(start=1, end=1000, step=3)

In [77]:
one_to_n

tensor([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,  40,
         43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,  79,  82,
         85,  88,  91,  94,  97, 100, 103, 106, 109, 112, 115, 118, 121, 124,
        127, 130, 133, 136, 139, 142, 145, 148, 151, 154, 157, 160, 163, 166,
        169, 172, 175, 178, 181, 184, 187, 190, 193, 196, 199, 202, 205, 208,
        211, 214, 217, 220, 223, 226, 229, 232, 235, 238, 241, 244, 247, 250,
        253, 256, 259, 262, 265, 268, 271, 274, 277, 280, 283, 286, 289, 292,
        295, 298, 301, 304, 307, 310, 313, 316, 319, 322, 325, 328, 331, 334,
        337, 340, 343, 346, 349, 352, 355, 358, 361, 364, 367, 370, 373, 376,
        379, 382, 385, 388, 391, 394, 397, 400, 403, 406, 409, 412, 415, 418,
        421, 424, 427, 430, 433, 436, 439, 442, 445, 448, 451, 454, 457, 460,
        463, 466, 469, 472, 475, 478, 481, 484, 487, 490, 493, 496, 499, 502,
        505, 508, 511, 514, 517, 520, 523, 526, 529, 532, 535, 5

# Tensor datatypes

In [84]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype is the tensor (e.g. float32 or float 16)
                             device=None, # what device is your tensor on
                             requires_grad=False) # whether or not to track gradients witth tensor operations

In [81]:
float_32_tensor

tensor([3., 6., 9.])

> # TENSOR DATATYPES IS ONE OF THE 3 BIG ERRORS YOU WILL RUN INTO WITH PYTORCH AND DEEP LEARNING
> TENSORS NOT RIGHT DATATYPE
>
> TENSORS NOT RIGHT SHAPE  `LL GIVE ERROR IN MATRIX MULTIPLICATION IF SHAPE DOESNT GET ALIGNED`
>
> TENSORS NOT ON THE RIGHT DEVICE

In [85]:
float_16_tensors= float_32_tensor.type(torch.float16)

In [86]:
float_16_tensors

tensor([3., 6., 9.], dtype=torch.float16)

In [87]:
float_16_tensors * float_32_tensor

tensor([ 9., 36., 81.])

In [89]:
float_16_tensors+float_32_tensor

tensor([ 6., 12., 18.])

In [110]:
x= torch.rand(6,3)
y= torch.rand(1,3)
print(x*y)
print(x)
print(y)

tensor([[0.1503, 0.1178, 0.4682],
        [0.1865, 0.0157, 0.3021],
        [0.1852, 0.3509, 0.7628],
        [0.1330, 0.3310, 0.6446],
        [0.2269, 0.0805, 0.0268],
        [0.0790, 0.3937, 0.1665]])
tensor([[0.6268, 0.1811, 0.5860],
        [0.7779, 0.0241, 0.3781],
        [0.7723, 0.5394, 0.9547],
        [0.5547, 0.5088, 0.8068],
        [0.9462, 0.1237, 0.0335],
        [0.3296, 0.6052, 0.2084]])
tensor([[0.2398, 0.6506, 0.7990]])


In [115]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [116]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [117]:
# here above even different datatypes are able to multiply without giving any error but they migh give error in some cases so for now leave it

In [146]:
# create a tensor
some_tensor = torch.rand(3,4).to(device) # do .to(device) to get the tensor on gpu and need to do everytime to get on gpu instead of cpu
some_tensor

tensor([[0.6220, 0.3248, 0.0953, 0.4558],
        [0.4079, 0.1440, 0.1786, 0.3351],
        [0.3244, 0.9482, 0.0132, 0.4393]], device='cuda:0')

In [147]:
print(some_tensor)

tensor([[0.6220, 0.3248, 0.0953, 0.4558],
        [0.4079, 0.1440, 0.1786, 0.3351],
        [0.3244, 0.9482, 0.0132, 0.4393]], device='cuda:0')


In [133]:
print(f" Datatype of tensor: {some_tensor.dtype}\nShape of tensor: {some_tensor.shape}\nSize of tensor: {some_tensor.size()}\nTensor is on: {some_tensor.device}")

 Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Size of tensor: torch.Size([3, 4])
Tensor is on: cpu


In [130]:
import torch

# Device setup - ek baar set kar, sab jagah use kar
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print(f"Using device: {device}")
if device.type == 'cuda':
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

# Ab har tensor/model ko device pe bhej
# Example:
# x = torch.rand(3, 4).to(device)
# model = YourModel().to(device)

Using device: cuda
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
Memory: 6.44 GB


In [126]:
# Tensors
x = torch.rand(100, 100).to(device)
y = torch.ones(10, 5).to(device)


### Manipulating Tensors( tensor operations)
> `Tensor operations include:`
>
> addition
>
> substraction
>
> multiplication (element-wise)
>
> division
>
> matrix multiplication`

In [135]:
tensor= torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [136]:
# multiply tensor by 10
tensor *10

tensor([10, 20, 30])

In [137]:
# subtract 10
tensor-19

tensor([-18, -17, -16])

In [139]:
#try out pytorch in built functions
torch.mul(tensor, 10)
# .mul to multiply .add to add

tensor([10, 20, 30])

In [141]:
torch.add(tensor,12)

tensor([13, 14, 15])

In [142]:
tensor

tensor([1, 2, 3])

In [144]:
tensor=torch.add(tensor,12)

In [145]:
tensor

tensor([13, 14, 15])

### Matrix multiplication
> Two main ways of performing multiplication in neural networks and deep learning :
>
> Element wise multiplication
>
> matrix multiplication (dot product)
>

In [149]:
torch.matmul(tensor, tensor)

tensor(590)

In [150]:
tensor

tensor([13, 14, 15])

In [151]:
# matrix multiplication by hand

In [152]:
13*13+14*14+15*15

590

In [165]:
%%time
value=0
for i in range(len(tensor)):
    value+= tensor[i]*tensor[i]
print(value)
#dont use this, use torch.mul() only  for matrix multiplication

tensor(590)
CPU times: total: 0 ns
Wall time: 1.46 ms


In [167]:
%%time

import torch

# Bada tensor bana - CPU pe
size = 10000
tensor = torch.rand(size, size)  # 10000x10000 matrix

# Heavy matrix operations - CPU pe
result = torch.mm(tensor, tensor)  # Matrix multiplication
result = torch.mm(result, tensor)  # Ek aur baar
result = torch.mm(result, tensor)  # Aur ek baar

# Element-wise operations
for _ in range(5):
    result = result * 2
    result = torch.sin(result)
    result = torch.cos(result)

print("Done!")
print(f"Result shape: {result.shape}")

Done!
Result shape: torch.Size([10000, 10000])
CPU times: total: 2min 8s
Wall time: 16.8 s


In [178]:
import time


# GPU Version
print("\n=== GPU ===")
start = time.time()
tensor_gpu = torch.rand(10000, 10000).to(device)
result_gpu = torch.mm(tensor_gpu, tensor_gpu)
result_gpu = torch.mm(result_gpu, tensor_gpu)
gpu_time = time.time() - start
print(f"GPU Time: {gpu_time:.2f} seconds")

print(f"\nSpeedup: {cpu_time/gpu_time:.2f}x faster on GPU")


=== GPU ===
GPU Time: 0.34 seconds

Speedup: 30.82x faster on GPU


In [179]:
### One of the most common errors in deep learning is the shape error

# THERE ARE TWO MAIN RULES THAT PERFORMING MATRIX MULTIPLICATION NEEDS TO SATISFY:
> THE **inner dimensions** must match:
>
> `(3,2) @ (3,2)` this wont work
>
> `(2,3) @ (3,2)` this will work
>
> `(3,2) @ (2,3)` this will work
>
> The resulting matrix has the shape of the **outer dimensions:**
>
> `(2,3)@(3,2) -> (2,2)`
>
> `(3,2)@(2,3) -> (3,3)`

In [181]:
torch.matmul(torch.rand(2,3), torch.rand(3,4))

tensor([[0.6418, 0.7615, 0.4781, 0.5040],
        [0.5422, 0.8010, 0.2379, 0.2308]])

In [182]:
# Shapes for matrix multiplication
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

In [183]:
tensor_B=torch.tensor([[7,8],
                       [9,10],
                       [11,12]])
torch.mm(tensor_A, tensor_B) # torch.mm() is same as torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [185]:
tensor_A.shape

torch.Size([3, 2])

In [186]:
tensor_B.shape

torch.Size([3, 2])

## To fix our tensor shape  issues, we can manipulate the shape of one of our tensors using  **transpose**
 >
 > a **transpose** switches the axes or dimensions of a given tensor

In [188]:
tensor_B.T, tensor_B

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]))

In [189]:
tensor_B.T.size()

torch.Size([2, 3])

In [190]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Tensor b after tensor_b.t still have same information even after transposing the matrix

# Finding the min , max, mean, sum etch (tensor aggregation)

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

#create a tensor
x=torch.arange(0,100,10)
x

2.10.0+cu126


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [3]:
import pandas as pd

In [4]:
print(pd)

<module 'pandas' from 'E:\\AI-ML-Learning\\.venv\\Lib\\site-packages\\pandas\\__init__.py'>


In [5]:
print(np)

<module 'numpy' from 'C:\\Users\\hp\\AppData\\Local\\Python\\pythoncore-3.14-64\\Lib\\site-packages\\numpy\\__init__.py'>


In [7]:
print(plt)

<module 'matplotlib.pyplot' from 'E:\\AI-ML-Learning\\.venv\\Lib\\site-packages\\matplotlib\\pyplot.py'>


In [8]:
# Ye run kar
import sys
print('pandas' in sys.modules)  # True = already loaded
print('numpy' in sys.modules)
print('matplotlib' in sys.modules)

True
True
True


In [9]:
# creating a tensor
x=torch.arange(0,100,10)

In [10]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
# find the min
torch.min(x)

tensor(0)

In [12]:
torch.max(x)

tensor(90)

In [14]:
torch.mean(x)

# will give another common error of tensors that is tensor not of correct datatype

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [16]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [17]:
# find the mean: note: the torch.mean() function requires a tensor of float32 datatype to work

In [18]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

In [20]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of targt tensor where the minimum value occurs
x.argmin()


tensor(0)

In [24]:
x[0]

tensor(0)

In [27]:
x=torch.arange(1,100)

In [28]:
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
x.argmax()

tensor(98)

In [30]:
x[98]

tensor(99)

# RESHAPING, STACKING, SQUEEZING AND UNSQUEEZING TENSORS
> Reshaping: `reshapes an input tensor to a defined shape`
>
> view: `return a view of an input tensor of certain shape but keep the same memory as the original tensor`
>
> stacking: `combine multiple tensors on top of each other (vstack) or side byside (hstack)`
>
> squeeze: `removes all `1` dimensions from a tensor`
>
> unsqueeze: `add a `1` dimension to a target tensor`
>
> premute: `return a view of the input with dimensions permuted (swapped) in a certain way`

In [32]:
#Lets create a tensor
import torch
x=torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [34]:
# Add an extra dimension
x_reshaped=x.reshape(1,9)

In [35]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [36]:
x_reshaped2=x.reshape(-1,9) # yaha pr -1 ka mtlb h khud calculate krlo, here -1,9 me row , coloumn ie 9 is number of columns so pytorch willl decide kitne rows hone chahiye 9/9 = 1 row!!
x_reshaped2

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [50]:
x_reshaped3=x.reshape(-1,3)
x_reshaped3

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [39]:
x_reshaped4=x.reshape(9,1)
x_reshaped4

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [42]:
x_reshaped5=x.reshape(3,3)
x_reshaped5

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [51]:
# Change the view
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
# Changing z changes x beczuse a view of a tensor shares the same memory as the origiinal tensor
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [66]:
#stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=0)

In [67]:
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [79]:
x_squeezed=x_stacked.squeeze()

In [80]:
x_squeezed

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
x_unsqueezed=x_stacked.unsqueeze(0)

In [76]:
x_unsqueezed

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [72]:
x_stacked=torch.arange(1,10,1)

In [73]:
x_stacked

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
x_stacked.shape

torch.Size([9])

In [82]:
x_reshaped.shape

torch.Size([1, 9])

In [83]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [84]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [86]:
x_reshaped.unsqueeze(0)

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [89]:
# torch.permute - rearranges the dimensions of a target tensors in a specified order
x_original= torch.rand(size=(224,224,3))# [height, width, colour_channels]

#permute is a view and as we discussed view shares the same memory as the tensor
# permute the original tensor to rearrange the axis or dim order
x_permuted=x_original.permute(2,0,1) # shifts axis 0-> 1 ,1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New_shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New_shape: torch.Size([3, 224, 224])


In [91]:
x_original[0,0,0]

tensor(0.2396)

In [92]:
x_original

tensor([[[0.2396, 0.1245, 0.8337],
         [0.6862, 0.3021, 0.0700],
         [0.5828, 0.1011, 0.1079],
         ...,
         [0.4326, 0.1300, 0.0586],
         [0.0559, 0.4267, 0.2238],
         [0.8687, 0.8016, 0.8923]],

        [[0.3345, 0.6364, 0.7422],
         [0.6368, 0.0935, 0.4761],
         [0.5819, 0.4561, 0.8120],
         ...,
         [0.5301, 0.3633, 0.7051],
         [0.1890, 0.6921, 0.6175],
         [0.5459, 0.8865, 0.6279]],

        [[0.8689, 0.8487, 0.6966],
         [0.6576, 0.5514, 0.7077],
         [0.9509, 0.5287, 0.2393],
         ...,
         [0.4503, 0.1787, 0.9468],
         [0.6376, 0.9906, 0.0204],
         [0.2547, 0.7447, 0.7098]],

        ...,

        [[0.1282, 0.8277, 0.8496],
         [0.5554, 0.2007, 0.6653],
         [0.3221, 0.6077, 0.1688],
         ...,
         [0.2657, 0.9883, 0.3585],
         [0.3320, 0.3062, 0.7482],
         [0.3031, 0.5981, 0.0620]],

        [[0.5737, 0.9194, 0.0043],
         [0.7297, 0.3681, 0.4808],
         [0.

In [94]:
x_original[0,0,0]=728218 # replacing value at position [0,0,0] with 728218
x_original[0,0,0] , x_permuted[0,0,0] # and since permute is a view function therefore original me change krne pr permute me bhi change hogyaaa 000 wale location pr wali value

(tensor(728218.), tensor(728218.))

# Indexing (Selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy.

In [95]:
# Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)

In [96]:
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [97]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [98]:
x[0][0]

tensor([1, 2, 3])

In [99]:
x[0][0][0]

tensor(1)

In [101]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [102]:
#Get all values of 0th and 1st dimensions but only index 1 or 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [103]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [104]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])